name: Laravel

on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.3.31'
    - uses: actions/checkout@v2
      with:
        github_token: '${{ secrets.GITHUB_TOKEN }}'
        branch: '${{ github.ref }}'
    - name: Setup .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Building
      run: composer install --prefer-dist --no-progress
    - name: Generate key
      run: |
          php artisan key:generate
          php artisan cache:clear
    - name: Send email
      uses: dawidd6/action-send-mail@v2
      with:
          server_address: smtp.gmail.com
          server_port: 587
          username: phamcongquochung558247@gmail.com
          password: 0977083561Hung
          subject: Github Actions job result
          # Literal body:
          body: Build job of ${{github.repository}} completed successfully!
          to: phamcongquochung2000@gmail.com
          from: phamcongquochung558247@gmail.com
          # Optional carbon copy recipients
          cc: kyloren@starkiller.com,leia@alderaan.com
          # Optional blind carbon copy recipients
          bcc: r2d2@jakku.com,hansolo@milleniumfalcon.com
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: attachments.zip,git.diff,./dist/static/main.js
    - name: Directory Permissions  
      run: chmod -R 777 storage bootstrap/cache
